### ISSUE TITLE
Conflict between language tool dependency and ngram feature extractors

### ISSUE THREAD

**Issue by andreahorbach** [ltl-ude/escrito#33]
adding 
<dependency>
		<groupId>de.tudarmstadt.ukp.dkpro.core</groupId>
		<artifactId>de.tudarmstadt.ukp.dkpro.core.languagetool-asl</artifactId>
		<version>1.8.0</version>
		</dependency>
to features pom causes ngram feature extractor tests to fail:
java.lang.NoClassDefFoundError: org/apache/lucene/codecs/CompoundFormat
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:67)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:47)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:37)
	at org.apache.lucene.codecs.Codec.<clinit>(Codec.java:41)
	at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:122)
	at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:148)
	at org.dkpro.tc.features.ngram.meta.LuceneMC.initializeWriter(LuceneMC.java:88)
	at org.dkpro.tc.features.ngram.meta.LuceneMC.initialize(LuceneMC.java:71)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:262)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:169)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:331)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:448)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:139)
	at de.unidue.ltl.escrito.features.ngrams.PosNGramsNormalizedFeatureExtractorTest.runMetaCollection(PosNGramsNormalizedFeatureExtractorTest.java:112)
	at de.unidue.ltl.escrito.features.ngrams.LuceneMetaCollectionBasedFeatureTestBase.runTest(LuceneMetaCollectionBasedFeatureTestBase.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.codecs.CompoundFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 56 more

**Comment by andreahorbach** [comment]
Seem to be a problem around the right version of 

```
<dependency>
<groupId>org.apache.lucene</groupId>
<artifactId>lucene-core</artifactId>
</dependency>
```

but I can't figure out how to get it to work. @zesch could you have a look?

**Comment by zesch** [comment]
I have run into this problem before. We currently cannot use ngram features and language-tool at the same time.
No easy solutions at the moment.

**Comment by andreahorbach** [comment]
Ok, then Language Tool goes as a preprocessing step into its own module, writes the features to a text file and we read this file in the feature extractor. We did that before.
